# Generated by Django 3.0.5 on 2020-04-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_auto_20200424_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='departure_date',
            field=models.DateField(blank=True, verbose_name='Data de Saída'),
        ),
    ]
